AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 80
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 80

Style/FrozenStringLiteralComment:
  Enabled: false
